fix: bypass requirements (#935)
Due to a regression in the code, as per `v2.8.12`, clicking the `Bypass
Requirements Check` toggle in the settings isn't working correctly and
results in the following devtools error log: `Uncaught (in promise)
TypeError: Cannot read properties of null (reading 'checked') at
HTMLInputElement.onchange [as __change]`

This pull request amends this behavior and returns the toggle to it's
functional state.